# Generated by Django on adding narrative models
import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameProject",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "owner",
                    models.ForeignKey(
                        related_name="owned_game_projects",
                        to=settings.AUTH_USER_MODEL,
                        null=True,
                        blank=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="DialogueNode",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("character", models.CharField(max_length=200)),
                ("text", models.TextField()),
                (
                    "node_type",
                    models.CharField(
                        max_length=20,
                        choices=[("statement", "statement"), ("question", "question"), ("option", "option")],
                        default="statement",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        related_name="dialogue_nodes",
                        to="core.gameproject",
                        on_delete=django.db.models.deletion.CASCADE,
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="DialogueLink",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("condition", models.CharField(max_length=200, blank=True)),
                ("action", models.CharField(max_length=200, blank=True)),
                (
                    "from_node",
                    models.ForeignKey(
                        related_name="out_links",
                        to="core.dialoguenode",
                        on_delete=django.db.models.deletion.CASCADE,
                    ),
                ),
                (
                    "to_node",
                    models.ForeignKey(
                        related_name="in_links",
                        to="core.dialoguenode",
                        on_delete=django.db.models.deletion.CASCADE,
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="CharacterStat",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("value", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                (
                    "project",
                    models.ForeignKey(
                        related_name="character_stats",
                        to="core.gameproject",
                        on_delete=django.db.models.deletion.CASCADE,
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]


