# Generated by Django 5.2.6 on 2025-09-08 17:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ai_editor_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCheck',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill', models.CharField(choices=[('logic', 'Logic'), ('encyclopedia', 'Encyclopedia'), ('rhetoric', 'Rhetoric'), ('drama', 'Drama'), ('conceptualization', 'Conceptualization'), ('visual_calculus', 'Visual Calculus'), ('volition', 'Volition'), ('inland_empire', 'Inland Empire'), ('empathy', 'Empathy'), ('authority', 'Authority'), ('suggestion', 'Suggestion'), ('espirit_de_corps', 'Espirit de Corps'), ('endurance', 'Endurance'), ('pain_threshold', 'Pain Threshold'), ('physical_instrument', 'Physical Instrument'), ('electrochemistry', 'Electrochemistry'), ('shivers', 'Shivers'), ('half_light', 'Half Light'), ('hand_eye_coordination', 'Hand/Eye Coordination'), ('perception', 'Perception'), ('reaction_speed', 'Reaction Speed'), ('savoir_faire', 'Savoir Faire'), ('interfacing', 'Interfacing'), ('composure', 'Composure')], max_length=30)),
                ('difficulty', models.CharField(choices=[('trivial', 'Trivial (5)'), ('easy', 'Easy (10)'), ('medium', 'Medium (15)'), ('hard', 'Hard (20)'), ('extreme', 'Extreme (25)'), ('impossible', 'Impossible (30)')], default='medium', max_length=20)),
                ('dc_value', models.IntegerField(default=15)),
                ('description', models.TextField(blank=True)),
                ('success_text', models.TextField(blank=True)),
                ('failure_text', models.TextField(blank=True)),
                ('critical_success_text', models.TextField(blank=True)),
                ('critical_failure_text', models.TextField(blank=True)),
                ('dialogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_checks', to='core.dialogue')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RollResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dice_roll', models.IntegerField()),
                ('skill_value', models.IntegerField()),
                ('total', models.IntegerField()),
                ('is_success', models.BooleanField()),
                ('is_critical_success', models.BooleanField(default=False)),
                ('is_critical_failure', models.BooleanField(default=False)),
                ('result_text', models.TextField(blank=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roll_results', to='core.character')),
                ('skill_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roll_results', to='core.skillcheck')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DialogueOption',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('dialogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.dialogue')),
                ('skill_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='options', to='core.skillcheck')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
