# Generated by Django 5.2.6 on 2025-09-12 14:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_quest_dialoguelog_questcharacter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('format_type', models.CharField(choices=[('json', 'JSON'), ('yaml', 'YAML'), ('xml', 'XML'), ('csv', 'CSV'), ('unity', 'Unity ScriptableObject'), ('unreal', 'Unreal Engine Data Table'), ('godot', 'Godot Resource'), ('renpy', "Ren'Py Script"), ('twine', 'Twine Story Format')], max_length=20)),
                ('template_content', models.TextField(help_text='Шаблон в формате Jinja2')),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dialogueoption',
            name='color',
            field=models.CharField(default='#3B82F6', help_text='Цвет опции в hex формате', max_length=7),
        ),
        migrations.AddField(
            model_name='dialogueoption',
            name='condition_met',
            field=models.BooleanField(default=True, help_text='Выполнено ли условие'),
        ),
        migrations.AddField(
            model_name='dialogueoption',
            name='condition_text',
            field=models.TextField(blank=True, help_text='Условие доступности опции'),
        ),
        migrations.AddField(
            model_name='dialogueoption',
            name='icon',
            field=models.CharField(default='💬', help_text='Иконка опции', max_length=50),
        ),
        migrations.AddField(
            model_name='dialogueoption',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Дополнительные данные'),
        ),
        migrations.AddField(
            model_name='dialogueoption',
            name='next_dialogue',
            field=models.ForeignKey(blank=True, help_text='Следующий диалог при выборе этой опции', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_options', to='core.dialogue'),
        ),
        migrations.AddField(
            model_name='dialogueoption',
            name='next_post',
            field=models.ForeignKey(blank=True, help_text='Следующий пост при выборе этой опции', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_options', to='core.post'),
        ),
        migrations.AddField(
            model_name='dialogueoption',
            name='option_type',
            field=models.CharField(choices=[('response', 'Ответ игрока'), ('choice', 'Выбор действия'), ('skill_check', 'Проверка навыка'), ('condition', 'Условный переход')], default='response', max_length=20),
        ),
        migrations.AddField(
            model_name='dialogueoption',
            name='required_skill',
            field=models.CharField(blank=True, help_text='Требуемый навык', max_length=30),
        ),
        migrations.AddField(
            model_name='dialogueoption',
            name='required_skill_value',
            field=models.IntegerField(blank=True, help_text='Минимальное значение навыка', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='color',
            field=models.CharField(default='#6B7280', help_text='Цвет поста', max_length=7),
        ),
        migrations.AddField(
            model_name='post',
            name='has_options',
            field=models.BooleanField(default=False, help_text='Есть ли у этого поста опции ответа'),
        ),
        migrations.AddField(
            model_name='post',
            name='icon',
            field=models.CharField(default='💬', help_text='Иконка поста', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='is_branching_point',
            field=models.BooleanField(default=False, help_text='Является ли точкой ветвления'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('statement', 'Утверждение'), ('question', 'Вопрос'), ('action', 'Действие'), ('narration', 'Повествование')], default='statement', max_length=20),
        ),
        migrations.AlterField(
            model_name='character',
            name='authority',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='composure',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='conceptualization',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='drama',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='electrochemistry',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='empathy',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='encyclopedia',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='endurance',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='espirit_de_corps',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='half_light',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='hand_eye_coordination',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='inland_empire',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='interfacing',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='logic',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='pain_threshold',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='perception',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='physical_instrument',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='reaction_speed',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='rhetoric',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='savoir_faire',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='shivers',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='suggestion',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='visual_calculus',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='volition',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='dialogueoption',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Доступна ли опция'),
        ),
        migrations.AlterField(
            model_name='dialogueoption',
            name='order',
            field=models.IntegerField(default=0, help_text='Порядок отображения'),
        ),
        migrations.AlterField(
            model_name='dialogueoption',
            name='text',
            field=models.TextField(help_text='Текст опции'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='difficulty_level',
            field=models.IntegerField(default=1, help_text='Уровень сложности от 1 до 20', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterUniqueTogether(
            name='dialogueoption',
            unique_together={('dialogue', 'order')},
        ),
        migrations.CreateModel(
            name='ExportSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format_type', models.CharField(choices=[('json', 'JSON'), ('yaml', 'YAML'), ('xml', 'XML'), ('csv', 'CSV'), ('unity', 'Unity ScriptableObject'), ('unreal', 'Unreal Engine Data Table'), ('godot', 'Godot Resource'), ('renpy', "Ren'Py Script"), ('twine', 'Twine Story Format')], default='json', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'Обрабатывается'), ('completed', 'Завершен'), ('failed', 'Ошибка')], default='pending', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('export_options', models.JSONField(blank=True, default=dict)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_sessions', to='core.gameproject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
