# Generated by Django 5.2.6 on 2025-09-20 16:04

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_exporttemplate_dialogueoption_color_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['name'], 'verbose_name': 'Character', 'verbose_name_plural': 'Characters'},
        ),
        migrations.AlterModelOptions(
            name='quest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='quest',
            name='dialogue',
        ),
        migrations.AddField(
            model_name='character',
            name='intellect',
            field=models.IntegerField(default=2, help_text='Intellect attribute (1-20)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='character',
            name='motorics',
            field=models.IntegerField(default=2, help_text='Motorics attribute (1-20)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='character',
            name='physique',
            field=models.IntegerField(default=2, help_text='Physique attribute (1-20)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='character',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project this character belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='core.gameproject'),
        ),
        migrations.AddField(
            model_name='character',
            name='psyche',
            field=models.IntegerField(default=2, help_text='Psyche attribute (1-20)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='dialogueoption',
            name='quest_completion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completion_options', to='core.quest'),
        ),
        migrations.AddField(
            model_name='dialogueoption',
            name='quest_trigger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trigger_options', to='core.quest'),
        ),
        migrations.AddField(
            model_name='quest',
            name='color',
            field=models.CharField(default='#10B981', help_text='Цвет квеста', max_length=7),
        ),
        migrations.AddField(
            model_name='quest',
            name='completion_dialogue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quest_completions', to='core.dialogue'),
        ),
        migrations.AddField(
            model_name='quest',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Дедлайн квеста', null=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='experience_reward',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quest',
            name='failure_dialogue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quest_failures', to='core.dialogue'),
        ),
        migrations.AddField(
            model_name='quest',
            name='icon',
            field=models.CharField(default='📋', help_text='Иконка квеста', max_length=50),
        ),
        migrations.AddField(
            model_name='quest',
            name='item_rewards',
            field=models.JSONField(blank=True, default=list, help_text='Награды предметов'),
        ),
        migrations.AddField(
            model_name='quest',
            name='max_progress',
            field=models.IntegerField(default=100, help_text='Максимальный прогресс'),
        ),
        migrations.AddField(
            model_name='quest',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Дополнительные данные'),
        ),
        migrations.AddField(
            model_name='quest',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='unlocks', to='core.quest'),
        ),
        migrations.AddField(
            model_name='quest',
            name='priority',
            field=models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий'), ('critical', 'Критический')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='quest',
            name='progress',
            field=models.IntegerField(default=0, help_text='Прогресс выполнения от 0 до 100'),
        ),
        migrations.AddField(
            model_name='quest',
            name='quest_giver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_quests', to='core.npc'),
        ),
        migrations.AddField(
            model_name='quest',
            name='required_items',
            field=models.JSONField(blank=True, default=list, help_text='Требуемые предметы'),
        ),
        migrations.AddField(
            model_name='quest',
            name='required_skills',
            field=models.JSONField(blank=True, default=dict, help_text="Требуемые навыки: {'skill_name': min_value}"),
        ),
        migrations.AddField(
            model_name='quest',
            name='skill_rewards',
            field=models.JSONField(blank=True, default=dict, help_text="Награды навыков: {'skill_name': bonus}"),
        ),
        migrations.AddField(
            model_name='quest',
            name='start_dialogue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quest_starts', to='core.dialogue'),
        ),
        migrations.AddField(
            model_name='quest',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Теги квеста'),
        ),
        migrations.AddField(
            model_name='quest',
            name='time_limit',
            field=models.DurationField(blank=True, help_text='Временное ограничение', null=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='quest_type',
            field=models.CharField(choices=[('dialogue', 'Диалог'), ('combat', 'Бой'), ('skill_check', 'Проверка навыка'), ('exploration', 'Исследование'), ('puzzle', 'Головоломка'), ('social', 'Социальное взаимодействие'), ('fetch', 'Доставка'), ('elimination', 'Устранение'), ('escort', 'Эскорт'), ('investigation', 'Расследование')], default='dialogue', max_length=20),
        ),
        migrations.AlterField(
            model_name='quest',
            name='status',
            field=models.CharField(choices=[('available', 'Доступен'), ('active', 'Активен'), ('completed', 'Завершен'), ('failed', 'Провален'), ('locked', 'Заблокирован'), ('paused', 'Приостановлен')], default='available', max_length=20),
        ),
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model', models.CharField(default='anthropic/claude-3.5-sonnet', max_length=100)),
                ('temperature', models.FloatField(default=0.7, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)])),
                ('max_tokens', models.IntegerField(default=1000, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4000)])),
                ('system_prompt', models.TextField(blank=True, help_text='Кастомный системный промпт')),
                ('is_enabled', models.BooleanField(default=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_config', to='core.gameproject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_name', models.CharField(blank=True, max_length=200)),
                ('context', models.JSONField(blank=True, default=dict, help_text='Контекст проекта (жанр, тональность, персонажи)')),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='core.gameproject')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('assistant', 'ИИ-помощник'), ('system', 'Система')], max_length=20)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Метаданные (модель, токены, время ответа)')),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestObjective',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('objective_type', models.CharField(choices=[('dialogue', 'Диалог'), ('kill', 'Убить'), ('collect', 'Собрать'), ('deliver', 'Доставить'), ('reach', 'Достичь'), ('interact', 'Взаимодействовать'), ('skill_check', 'Проверка навыка'), ('time_limit', 'Временное ограничение')], default='dialogue', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_optional', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('required_count', models.IntegerField(default=1, help_text='Требуемое количество')),
                ('current_count', models.IntegerField(default=0, help_text='Текущее количество')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Дополнительные данные цели')),
                ('completion_dialogue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objective_completions', to='core.dialogue')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='core.quest')),
                ('trigger_dialogue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objective_triggers', to='core.dialogue')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='dialogueoption',
            name='quest_objective_completion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completion_options', to='core.questobjective'),
        ),
        migrations.AddField(
            model_name='dialogueoption',
            name='quest_objective_trigger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trigger_options', to='core.questobjective'),
        ),
    ]
