# Generated by Django 5.2.6 on 2025-09-20 18:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_character_options_alter_quest_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Новый проект', max_length=200)),
                ('genre', models.CharField(default='', max_length=100)),
                ('setting', models.CharField(default='', max_length=200)),
                ('tone', models.CharField(default='dark-noir', max_length=50)),
                ('phase', models.CharField(default='idea', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('current_focus', models.CharField(blank=True, default='', max_length=200)),
                ('last_activity', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'project_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('characters', models.JSONField(blank=True, default=list)),
                ('events', models.JSONField(blank=True, default=list)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='core.projectsession')),
            ],
            options={
                'db_table': 'project_scenes',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ProjectQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('objectives', models.JSONField(blank=True, default=list)),
                ('rewards', models.JSONField(blank=True, default=list)),
                ('consequences', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='core.projectsession')),
            ],
            options={
                'db_table': 'project_quests',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMechanics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dice_system', models.CharField(default='d20', max_length=50)),
                ('stats', models.JSONField(blank=True, default=list)),
                ('voices', models.JSONField(blank=True, default=list)),
                ('checks', models.CharField(default='d20 + стат', max_length=100)),
                ('inventory', models.BooleanField(default=False)),
                ('reputation', models.BooleanField(default=False)),
                ('relationships', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mechanics', to='core.projectsession')),
            ],
            options={
                'db_table': 'project_mechanics',
            },
        ),
        migrations.CreateModel(
            name='ProjectCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(default='npc', max_length=50)),
                ('background', models.TextField(blank=True, default='')),
                ('motivation', models.TextField(blank=True, default='')),
                ('fears', models.JSONField(blank=True, default=list)),
                ('traits', models.JSONField(blank=True, default=list)),
                ('voices', models.JSONField(blank=True, default=list)),
                ('speech_style', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='core.projectsession')),
            ],
            options={
                'db_table': 'project_characters',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AgentMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_memories', to='core.projectsession')),
            ],
            options={
                'db_table': 'agent_memories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('priority', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.projectsession')),
            ],
            options={
                'db_table': 'project_tasks',
                'ordering': ['-priority', 'title'],
            },
        ),
    ]
